### ISSUE TITLE
Sunflare & Corona issues

### ISSUE THREAD

**Issue by Nyxilo** [LGhassen/Singularity#10]
[SingularityKopernicusPatch.zip](https://github.com/user-attachments/files/17098915/SingularityKopernicusPatch.zip)

Got an issue few years ago - half resolved as of today :

- Kerbol's Corona showing up in the Singularity (FIXED - using the provided .zip)

- Kerbol's sunflare (I guess it's scatterer's one) still showing up - but wait, a blackhole doesn't have a sunflare right? 

![screenshot662](https://github.com/user-attachments/assets/aae0ccd2-3bfe-4b6a-8b06-d7083521f5c8)

**Comment by LGhassen** [comment]
Well yeah these aren't issues with singularity, just like you disabled the Corona through Kopernicus, disable the associated scatterer sunflare when making a blackhole. Feel free to reopen this if you actually have an issue with singularity.
